export const ICONS = {
  mail: "E-Mails, Nachrichten, Antworten",
  calendar: "Termine, Planung, Meetings",
  checklist: "Allgemeine Aufgaben, Organisation",
  priority: "Wichtig, dringend, Fokus",
  work: "Arbeit, Job, Projekte",
  code: "Programmieren, Technik",
  study: "Lernen, Lesen, Recherche",
  creative: "Schreiben, Design, Ideen",
  health: "Gesundheit, Arzt",
  fitness: "Sport, Workout",
  home: "Haushalt, Zuhause",
  shopping: "Einkaufen",
  food: "Kochen, Essen",
  finance: "Finanzen, Rechnungen",
  admin: "Verwaltung, Dokumente",
  call: "Telefonate, Calls",
  travel: "Reisen, Unterwegs",
  maintenance: "Reparatur, Wartung",
  personal: "Privat, Familie",
  other: "Sonstiges, Unklar",
};