// export const ICONS = {
//   mail: "fluent:mail-20-regular",
//   calendar: "fluent:calendar-20-regular",
//   checklist: "fluent:task-list-20-regular",
//   priority: "fluent:flag-20-regular",
//   work: "fluent:briefcase-20-regular",
//   code: "fluent:code-20-regular",
//   study: "fluent:book-20-regular",
//   creative: "fluent:pen-20-regular",
//   health: "fluent:heart-20-regular",
//   fitness: "fluent:dumbbell-20-regular",
//   home: "fluent:home-20-regular",
//   shopping: "fluent:cart-20-regular",
//   food: "fluent:food-20-regular",
//   finance: "fluent:wallet-20-regular",
//   admin: "fluent:document-20-regular",
//   call: "fluent:call-20-regular",
//   travel: "fluent:airplane-20-regular",
//   maintenance: "fluent:wrench-screwdriver-20-regular",
//   personal: "fluent:person-20-regular",
//   other: "fluent:question-circle-20-regular",
// };


export const ICONS = {
  mail: "fluent:mail-20-filled",
  calendar: "fluent:calendar-20-filled",
  checklist: "fluent:task-list-20-filled",
  priority: "fluent:flag-20-filled",
  work: "fluent:briefcase-20-filled",
  code: "fluent:code-20-filled",
  study: "fluent:book-20-filled",
  creative: "fluent:pen-20-filled",
  health: "fluent:heart-20-filled",
  fitness: "fluent:dumbbell-20-filled",
  home: "fluent:home-20-filled",
  shopping: "fluent:cart-20-filled",
  food: "fluent:food-20-filled",
  finance: "fluent:wallet-20-filled",
  admin: "fluent:document-20-filled",
  call: "fluent:call-20-filled",
  travel: "fluent:airplane-20-filled",
  maintenance: "fluent:wrench-screwdriver-20-filled",
  personal: "fluent:person-20-filled",
  other: "fluent:question-circle-20-filled",
};
